<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LightBooksAgent.Application\LightBooksAgent.Application.csproj" />
    <ProjectReference Include="..\LightBooksAgent.Infrastructure\LightBooksAgent.Infrastructure.csproj" />
    <ProjectReference Include="..\LightBooksAgent.Workflows\LightBooksAgent.Workflows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
