<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LightBooksAgent.Core\LightBooksAgent.Core.csproj" />
    <ProjectReference Include="..\LightBooksAgent.Application\LightBooksAgent.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" Version="1.21.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.21.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
